// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5WuH2wnFBcmvT8R35L3_PcW1jrHp2zfA',
    appId: '1:591998557364:web:db1f59b9b4d6c832decbe1',
    messagingSenderId: '591998557364',
    projectId: 'ecommerce-35a84',
    authDomain: 'ecommerce-35a84.firebaseapp.com',
    storageBucket: 'ecommerce-35a84.firebasestorage.app',
    measurementId: 'G-PC0KMY2RE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWHOXwqn0FLv7Wp-cstO3tGo13zk19S4Y',
    appId: '1:591998557364:android:ccd2f01551ac58a7decbe1',
    messagingSenderId: '591998557364',
    projectId: 'ecommerce-35a84',
    storageBucket: 'ecommerce-35a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxlap2UAiRANCqbCC9d-7LD7VN3cwNyg',
    appId: '1:591998557364:ios:ff4c9d2b23a2356cdecbe1',
    messagingSenderId: '591998557364',
    projectId: 'ecommerce-35a84',
    storageBucket: 'ecommerce-35a84.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIxlap2UAiRANCqbCC9d-7LD7VN3cwNyg',
    appId: '1:591998557364:ios:ff4c9d2b23a2356cdecbe1',
    messagingSenderId: '591998557364',
    projectId: 'ecommerce-35a84',
    storageBucket: 'ecommerce-35a84.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5WuH2wnFBcmvT8R35L3_PcW1jrHp2zfA',
    appId: '1:591998557364:web:11f68fa5c8690ba2decbe1',
    messagingSenderId: '591998557364',
    projectId: 'ecommerce-35a84',
    authDomain: 'ecommerce-35a84.firebaseapp.com',
    storageBucket: 'ecommerce-35a84.firebasestorage.app',
    measurementId: 'G-H123H317P1',
  );
}
